# Required reaction-publish-semantic-release context variables:
#  NPM_TOKEN
version: 2

_defaults: &defaults
  docker:
    - image: cimg/node:14.21.3
  steps:
    - checkout

_restore_cache: &restore_cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

jobs:
  build:
    <<: *defaults
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    <<: *defaults
    steps:
      - *restore_cache
      - run: npx semantic-release

  lint:
    <<: *defaults
    steps:
      - *restore_cache
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - *restore_cache
      - run: npm run test

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          context:
            - reaction-publish-semantic-release
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          context:
            - reaction-publish-semantic-release
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
