# Required reaction-publish-semantic-release context variables:
#  NPM_TOKEN
version: 2.1

executors:
  node_executor:
    docker:
      - image: cimg/node:14.21.3
    working_directory: ~/repo

commands:
  setup_npm_auth:
    description: "Create .npmrc file with auth token"
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  save_cache:
    description: "Save node_modules cache"
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  restore_cache:
    description: "Restore node_modules cache"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

jobs:
  build:
    executor: node_executor
    steps:
      - checkout
      - setup_npm_auth
      - run: npm ci
      - save_cache

  deploy:
    executor: node_executor
    steps:
      - checkout
      - setup_npm_auth
      - restore_cache
      - run: npx semantic-release

  lint:
    executor: node_executor
    steps:
      - checkout
      - restore_cache
      - run: npm run lint

  test:
    executor: node_executor
    steps:
      - checkout
      - restore_cache
      - run: npm run test

workflows:
  build_deploy:
    jobs:
      - build:
          context:
            - reaction-publish-semantic-release
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          context:
            - reaction-publish-semantic-release
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
